_this addAction['Take an Assault Pack',RGT_fnc_smallbag,nil,1.5,true,true,"","((_target distance _this)<5)"];   
_this addAction['Take a Patrol Pack',RGT_fnc_bigbag,nil,1.5,true,true,"","((_target distance _this)<5)"];   
_this addAction['Take Small LR Radio',RGT_fnc_slr,nil,1.5,true,true,"","((_target distance _this)<5)"];   
_this addAction['Take Big LR Radio',RGT_fnc_blr,nil,1.5,true,true,"","((_target distance _this)<5)"];   
_this addAction['Take First Aid Bag',RGT_fnc_medbag,nil,1.5,true,true,"","((_target distance _this)<5)"];   
_this addAction['Take Sniper Bag',RGT_fnc_Sniperbag,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take M3 MAAWS',RGT_fnc_maws,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take Mortar Tube',RGT_fnc_Mortar_Tube,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take Mortar Ammo',RGT_fnc_Mortar_Ammo,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take MAAWs Ammo',RGT_fnc_MedAT_AmmoBearer,nil,1.5,true,true,"","((_target distance _this)<5)"];  
_this addAction['Take Gas Mask',RGT_fnc_Gasmask,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take a Cig Pack and Matches',RGT_fnc_CigsMatch,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take a Cigar and a Zippo',RGT_fnc_CigarZippo,nil,1.5,true,true,"","((_target distance _this)<5)"]; 
_this addAction['Take IHADSS Helmet',RGT_fnc_Ihadss,nil,1.5,true,true,"","((_target distance _this)<5)"];